### ISSUE TITLE
Backup Key

### ISSUE THREAD

**Issue by hofermart** [BitGo/wallet-recovery-wizard#112]
Hi there.
The program says I should enter the public key at box B. But that's in box C.
Are the two reversed?
best regards

**Comment by hofermart** [comment]
My Backup Key does not start with xpub... 
It's from May 2019

**Comment by hofermart** [comment]
Ok, the problem has been solved.
I downloaded the older version 2.6.5 so it works.
But now the program does not recognize my Bitcoin wallet address. Can someone help me there?
lg

**Comment by glowang** [comment]
@hofermart in order to help you we need to know more about which exact feature of the software you were using (Is it "Unsigned Sweep"? "Non-BitGo"?). What were you trying to accomplish? It would be helpful if we can also get a screenshot of the error you are seeing as well. 
Please **DO NOT** post any sensitive data here and forward your information to support@bitgo.com instead for privacy concerns. In your email to support, please include this link for reference. Please **DO NOT** send us your private key or password. If they are part of the screenshot, please hide them before you send your information to us. Thanks!

**Comment by hofermart** [comment]
I don't need help anymore. Everything's going wellThanks Am 05.01.21, 01:30 schrieb Gloria Wang <notifications@github.com>:

   
  @hofermart in order to help you we need to know more about which exact feature of the software you were using (Is it "Unsigned Sweep"? "Non-BitGo"?). What were you trying to accomplish? It would be helpful if we can also get a screenshot of the error you are seeing as well. Please DO NOT post any sensitive data here and forward your information to support@bitgo.com instead for privacy concerns. In your email to support, please include this link for reference. Please DO NOT send us your private key or password. If they are part of the screenshot, please hide them before you send your information to us. Thanks!

**Comment by glowang** [comment]
Danke @hofermart! We will close out this issue then :)
